os: linux
distro: bionic
arch: ppc64le
# before_install:
#   - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
#   - sudo apt-add-repository "deb [arch=ppc64le] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
#   - sudo apt-get update && sudo apt-get install packer
script: 
#   - sudo lxd init 
  -  cat <<EOF | lxd init --preseed
config:
  core.https_address: 192.168.1.1:9999
  images.auto_update_interval: 15
networks:
- name: lxdbr0
  type: bridge
  config:
    ipv4.address: auto
    ipv6.address: none
EOF
